server:
  port: 9011

spring:
  application:
    name: order-server

eureka:
  client:
    service-url:
        defaultZone: http://127.0.0.1:9121/eureka/

user-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule