spring:
  profiles:
    active: dev
    include: feign,sentinel
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: ${spring.profiles.active:public} # 使用 dev 命名空间下的配置

     # 作为注册中心
  application:
    name: nacos-order
logging:
  level:
    com.demo.feign: debug

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:nacos-order.yaml?group=order